/**
 * CHARACTER PORTRAIT GALLERY — Types
 *
 * Tracks generated character portraits with visual identity data
 * for style consistency across the gallery.
 */

export interface PortraitRecord {
  id: string;                     // UUID
  characterId: string;            // Character UUID
  imageUrl: string;               // Public URL (Supabase Storage)
  storagePath: string;            // Supabase Storage path
  prompt: string;                 // Full image gen prompt used
  model: string;                  // Model used (gpt-image-1, dall-e-3)
  label: string;                  // User-facing label (e.g. "Level 1 — The Beginning")
  milestone: PortraitMilestone;   // What triggered this portrait
  characterLevel: number;         // Level when generated
  createdAt: string;              // ISO timestamp
}

export type PortraitMilestone =
  | 'creation'       // Level 1 — first portrait
  | 'level-5'
  | 'level-10'
  | 'level-15'
  | 'level-20'
  | 'custom'         // Player-triggered
  | 'story-moment';  // Key narrative beat

export interface VisualIdentity {
  /** The reusable style/appearance prompt prefix — generated by Claude once,
   *  then prepended to every future portrait prompt for consistency. */
  promptPrefix: string;
  /** The art style descriptor (e.g. "fantasy oil painting, warm lighting") */
  artStyle: string;
  /** Generated timestamp */
  createdAt: string;
}

export interface CharacterGallery {
  characterId: string;
  visualIdentity: VisualIdentity | null;
  portraits: PortraitRecord[];
}

/** Default milestone labels */
export const MILESTONE_LABELS: Record<PortraitMilestone, string> = {
  'creation':      'The Beginning',
  'level-5':       'Rising Adventurer',
  'level-10':      'Seasoned Hero',
  'level-15':      'Legendary Champion',
  'level-20':      'Epic Destiny',
  'custom':        'Portrait',
  'story-moment':  'A Defining Moment',
};
